version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-for-debug:
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.prod.ts
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.ts
            - run: echo $GOOGLE_SVC | base64 --decode > google-services.json
            - run: npm install
            - run: npm run build
            - run: npx cap sync android
            - run: npx cap copy android
            - run: echo $GOOGLE_SVC | base64 --decode > android/app/google-services.json
            - run: python updateAndroid.py
            - run: cd android && ./gradlew build
            # npm install -D firebase-tools 
            - run: ./node_modules/.bin/firebase appdistribution:distribute android/app/build/outputs/apk/debug/app-debug.apk --app $APP_FIREBASE --release-notes "versao atualizada" --groups "develop" --token $FB_TOKEN
            - save_cache:
                key: node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
                paths: 
                - ~/project/node_modules
                - ~/.gradle
  build-home:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.prod.ts
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.ts
            - run: npm install
            - run: ./node_modules/@ionic/cli/bin/ionic build --prod
            ./node_modules/.bin/firebase deploy --only hosting --project dental-anesthesic --token $FB_TOKEN
            
  build-for-prod:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.prod.ts
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.ts
            - run: npm install
            - run: npm run build --prod
            - run: npx cap sync android
            - run: npx cap copy android
            - run: cd android
            - run: ./gradlew build
            - run: firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --app $APP_FIREBASE --release-notes "versao atualizada" --groups "develop" --token $FB_TOKEN
workflows:
  build-for-debug:
    jobs:
      - build-for-debug

  build-home:
    jobs:
      - build-home:
          filters:
              branches:
                only: develop

  build-for-prod:
    jobs:
      - build-for-prod:
          filters:
            branches:
              only: master
