version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.prod.ts
            - run: src/environments/environment.ts
            - run: npm install
            - run: npm run build
workflows:
    build-and-test:
      jobs:
        - build-and-test
