version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-for-debug:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.prod.ts
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.ts
            - run: npm install
            - run: npm run build
  build-for-prod:
    filters:
      branches:
        only: /master
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.prod.ts
            - run: echo $PROD_ENV | base64 --decode > src/environments/environment.ts
            - run: npm install
            - run: npm run build --prod
workflows:
    build-for-debug:
      jobs:
        - build-for-debug
    build-for-prod:
      jobs:
        - build-for-prod
